export const userData = [
  {
    id: 1,
    name: "Jane",
    message: "dummy content",
    time: "12/10/2020",
    notification: 1,
    read: true,
    status: false,
    voice: true,
  },
  {
    id: 2,
    name: "Johny",
    message: "dummy content",
    time: "Yesterday",
    // notification: 2,
    photo: true,
    voice: false,
  },
  {
    id: 3,
    name: "Akshay",
    message: "dummy content",
    time: "12/10/2020",
    notification: 1,
    photo: true,
    voice: true,
  },
  {
    id: 4,
    name: "Rahul",
    message: "dummy content",
    time: "Yesterday",
    // notification: 2,
    photo: true,
    voice: false,
  },
  {
    id: 5,
    name: "Monu Vishwakarma",
    message: "dummy content",
    time: "12/10/2020",
    notification: 2,
    photo: true,
    voice: true,
  },
  {
    id: 6,
    name: "Guptaji",
    message: "dummy content",
    time: "Yesterday",
    notification: 1,
    voice: true,
  },
  {
    id: 7,
    name: "Ankita",
    message: "dummy content",
    time: "Yesterday",
    notification: 5,
    read: true,
    voice: false,
  },
  {
    id: 8,
    name: "Sonam",
    message: "dummy content",
    time: "Yesterday",
    notification: 1,
    read: true,
    voice: true,
  },
];
